
#ifndef APPCONST_H_INCLUDED
#define APPCONST_H_INCLUDED
#define STUDENT_NAME_LEN 64
#define PROGRAM_NAME_LEN  32
#define EMAIL_LEN  64
#define STATUS_LEN 64
#define NUMBER_OF_STUDENTS 100

#endif // APPCONST_H_INCLUDED
